### ISSUE TITLE
Improved floor layout for double-deck aircraft

### ISSUE THREAD

**Issue by askprash** [MIT-LAE/TASOPT.jl#27]
Current implementation of the double deck aircraft splits the load equally between both decks - this influences the number of rows that are needed to accommodate the max number of passengers as well as the floor sizing (since load is just split in half between the floors currently) as well. 

We could improve this by appropriately reducing the number of seats (and therefore load) based on the location of the floors relative to the fuselage centerline.

**Comment by ngomezve** [comment]
Issue fixed in PR #59
