### ISSUE TITLE
Inconsistency in fuselage cross-section definition of the number of webs and bubble center offsets

### ISSUE THREAD

**Issue by askprash** [MIT-LAE/TASOPT.jl#61]
Fundamentally there is an inconsistency in how the number of fuselage webs (`nfweb`) for multi-bubble fuselages and the y-offset of the bubble centers (`wfb`) are being treated. If it is a single bubble then `wfb = 0.0` **and** `nfweb = 0`. However, the default inputs (which mainly showcase single-bubble) designs are all inconsistent as they set `nfweb = 1`. This seems to be a bug carried over from the FORTRAN code v2.16  where `getparams.f` hardcodes `nfweb = 1.0`. While this is harmless in some parts:
https://github.com/MIT-LAE/TASOPT.jl/blob/dc5e481d8417c60182e6ed5660f46c3b6aa9370f/src/structures/fuseW.jl#L159-L164

since `wfb=0.0` here means it doesn't matter what `nfweb` is. However, it does mess up the calculation here: 
https://github.com/MIT-LAE/TASOPT.jl/blob/dc5e481d8417c60182e6ed5660f46c3b6aa9370f/src/structures/fuseW.jl#L300-L304
 `nfweb = 1` leads to a wrong x-moment of inertia here (second term should be zero if single bubble).

A cleaner setup that avoids confusion is to specify the number of bubbles in the input and appropriately perform some checks before constructing the fuselage structures.  

I'm addressing this as part of the updates and clean-up in #57, but all the default sizing outputs in the tests will need to change ever so slightly.

**Comment by ngomezve** [comment]
Good realization! I also noticed that N_webs = 1 in the inputs seemed odd for single-bubble aircraft.

**Comment by askprash** [comment]
Addressed by #57
