### ISSUE TITLE
Floor sizing bug in `fusew`

### ISSUE THREAD

**Issue by askprash** [MIT-LAE/TASOPT.jl#68]
Noticed this when I started cleaning up the `fusew` function and the fuselage structures [here](https://github.com/MIT-LAE/TASOPT.jl/pull/57/commits/6aba28cdb70ef3138d8a4001e993ecd9592e6144) #57. This line here sets the max shear stress allowable in the floor beams to be equal to the maximum **bending stress**:
https://github.com/MIT-LAE/TASOPT.jl/blob/b02a90b58c2cf9cad655b204cd9c015a57d5623e/src/structures/fuseW.jl#L147
This seems to have been carried over from the FORTRAN code.

Most Al alloys have notably lower shear strength $\tau_{max} < \sigma_{max}$
This must be making the floors webs considerably thinner and therefore the floor weight is probably lower than it should be. 

@ngomezve / @aditeyashukla does this make sense? Or am I missing something?

Fixing in #57

**Comment by aditeyashukla** [comment]
Makes perfect sense - I noticed this too but thought it was just taking a rough estimate. I think it should be super easy to make it accurate now as we have material properties for the floor accessible/editable
