### ISSUE TITLE
Inconsistency in insulation calculation

### ISSUE THREAD

**Issue by askprash** [MIT-LAE/TASOPT.jl#70]
The insulation weight is estimated by assuming that some fraction (defaults to 55%) of the fuselage circle is part of the cabin and is insulated but the remaining 45% is part of the cargo hold that is not insulated. 

The existing calculation looks like this:
https://github.com/MIT-LAE/TASOPT.jl/blob/90a11ce611b7dee323d2b4dab7c57c618baf11e1/src/structures/fuseW.jl#L220-L224

Firstly, the 0.55 default factor implies it should be $2.2*\theta$ not $2.0*\theta$:
`Winsul = Wppinsul*((1.1*pi+2.2*thetafb)*Rfuse*lshell + 0.55*(Snose+Sbulk))`

Secondly, this does not actually take the perimeter correctly if there is a downward bubble shift.

Proposed fix is something like:
``` julia
  p = get_perimeter(layout.cross_section)
  A = p * layout.l_shell + S_nose + S_bulk
  W = weight_per_area * insulated_fraction * A

  shell_centroid = 0.5 * (layout.x_pressure_shell_fwd + layout.x_pressure_shell_aft)

  insulation = Weight(W = W, x = shell_centroid)
```
Fixing in #57

**Comment by askprash** [comment]
@ngomezve does this make sense to you?

A more "thorough" fix (probably later) would use the actual floor height and only add insulation for the portion of the cabin above the floor.

**Comment by ngomezve** [comment]
This is an improvement over the existing model. I agree that the insulated fraction parameter could be eliminated by using the actual cabin layout, but this is probably OK for now.
